apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
    - name: branch
      default: main
  tasks:
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup

    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)
      runAfter:
        - init

    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: flake8
      params:
      - name: image
        value: python:3.9-slim
      - name: args
        value: ["--count","--max-complexity=10","--max-line-length=127","--statistics"]
      runAfter:
        - clone

    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: nose
      params:
      - name: args
        value: "-v --with-spec --spec-color"
      runAfter:
        - lint

    # - name: deploy
    #   workspaces:
    #     - name: manifest-dir
    #       workspace: pipeline-workspace
    #   taskRef:
    #     name: kubectl
    #     kind: ClusterTask
    #   params:
    #   - name: SCRIPT
    #     value: |
    #       echo "Deploying to MicroK8s..."
    #       sudo microk8s kubectl apply -f deploy/
    #       sudo microk8s kubectl get pods -l app=accounts
    #   runAfter:
    #     - tests